//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "CameraPage.xaml.h"

void ::CutTheWords::Views::CameraPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///CameraPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::CutTheWords::Views::CameraPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->slider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->slider))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::CutTheWords::Views::CameraPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&CameraPage::slider_ValueChanged);
            }
            break;
        case 2:
            {
                this->ExtractButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ExtractButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::CutTheWords::Views::CameraPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&CameraPage::ExtractButton_Tapped);
            }
            break;
        case 3:
            {
                this->CameraButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->CameraButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::CutTheWords::Views::CameraPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&CameraPage::CameraButton_Tapped);
            }
            break;
        case 4:
            {
                this->PreviewControl = safe_cast<::Windows::UI::Xaml::Controls::CaptureElement^>(__target);
            }
            break;
        case 5:
            {
                this->ImageGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 6:
            {
                this->PreviewImage = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->PreviewImage))->SizeChanged += ref new ::Windows::UI::Xaml::SizeChangedEventHandler(this, (void (::CutTheWords::Views::CameraPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::SizeChangedEventArgs^))&CameraPage::PreviewImage_SizeChanged);
            }
            break;
        case 7:
            {
                this->TextOverlay = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 8:
            {
                this->title = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::CutTheWords::Views::CameraPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


