#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Button;
                ref class Image;
                ref class TextBlock;
            }
        }
    }
}

namespace CutTheWords
{
    namespace Views
    {
        [::Windows::Foundation::Metadata::WebHostHidden]
        partial ref class PicPage : public ::Windows::UI::Xaml::Controls::Page, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector,
            public ::Windows::UI::Xaml::Markup::IComponentConnector2
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
            virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
        
            private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
            private: ::Windows::UI::Xaml::Controls::Grid^ Image;
            private: ::Windows::UI::Xaml::Controls::Button^ SampleButton;
            private: ::Windows::UI::Xaml::Controls::Button^ LoadButton;
            private: ::Windows::UI::Xaml::Controls::Image^ PreviewImage;
            private: ::Windows::UI::Xaml::Controls::Grid^ TextOverlay;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ title;
        };
    }
}

