//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "PicPage.xaml.h"

void ::CutTheWords::Views::PicPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///PicPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::CutTheWords::Views::PicPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->RootGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 2:
            {
                this->Image = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 3:
            {
                this->SampleButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->SampleButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::CutTheWords::Views::PicPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&PicPage::SampleButton_Tapped);
            }
            break;
        case 4:
            {
                this->LoadButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->LoadButton))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::CutTheWords::Views::PicPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&PicPage::LoadButton_Tapped);
            }
            break;
        case 5:
            {
                this->PreviewImage = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->PreviewImage))->SizeChanged += ref new ::Windows::UI::Xaml::SizeChangedEventHandler(this, (void (::CutTheWords::Views::PicPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::SizeChangedEventArgs^))&PicPage::PreviewImage_SizeChanged);
            }
            break;
        case 6:
            {
                this->TextOverlay = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 7:
            {
                this->title = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::CutTheWords::Views::PicPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


