#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ScrollViewer;
                ref class CommandBar;
                ref class ListView;
                ref class StackPanel;
                ref class TextBox;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Animation {
                    ref class Storyboard;
                }
            }
        }
    }
}

namespace CutTheWords
{
    namespace Views
    {
        [::Windows::Foundation::Metadata::WebHostHidden]
        partial ref class SingleRootPage : public ::Windows::UI::Xaml::Controls::Page, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector,
            public ::Windows::UI::Xaml::Markup::IComponentConnector2
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
            virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
            class SingleRootPage_obj1_Bindings;
        
            ::XamlBindingInfo::XamlBindings^ Bindings;
            private: ::Windows::UI::Xaml::Controls::ScrollViewer^ scro;
            private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ FadOutEditPanel;
            private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ FadInEditPanel;
            private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ FadOutDelPanel;
            private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ FadInDelPanel;
            private: ::Windows::UI::Xaml::Controls::CommandBar^ topbar;
            private: ::Windows::UI::Xaml::Controls::ListView^ VocList;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ EditPanel;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ DelPanel;
            private: ::Windows::UI::Xaml::Controls::ListView^ DelList;
            private: ::Windows::UI::Xaml::Controls::TextBox^ block;
            private: ::Windows::UI::Xaml::Controls::ListView^ EditList;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ voc_root;
        };
    }
}

