#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class MediaElement;
                ref class ScrollViewer;
                ref class CommandBar;
                ref class TextBlock;
                ref class Button;
                ref class ListView;
                ref class StackPanel;
                ref class TextBox;
                ref class AppBarButton;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Animation {
                    ref class Storyboard;
                }
            }
        }
    }
}
namespace Microsoft {
    namespace Advertising {
        namespace WinRT {
            namespace UI {
                ref class AdControl;
            }
        }
    }
}

namespace CutTheWords
{
    namespace Views
    {
        [::Windows::Foundation::Metadata::WebHostHidden]
        partial ref class SingleVocPage : public ::Windows::UI::Xaml::Controls::Page, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector,
            public ::Windows::UI::Xaml::Markup::IComponentConnector2
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
            virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
            class SingleVocPage_obj1_Bindings;
        
            ::XamlBindingInfo::XamlBindings^ Bindings;
            private: ::Windows::UI::Xaml::Controls::MediaElement^ media;
            private: ::Windows::UI::Xaml::Controls::ScrollViewer^ scro;
            private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ FadOutEditPanel;
            private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ FadInEditPanel;
            private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ FadOutDelPanel;
            private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ FadInDelPanel;
            private: ::Windows::UI::Xaml::Controls::CommandBar^ topbar;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ tivoc;
            private: ::Windows::UI::Xaml::Controls::Button^ play_but;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ kk;
            private: ::Windows::UI::Xaml::Controls::ScrollViewer^ expst;
            private: ::Windows::UI::Xaml::Controls::ScrollViewer^ note_view;
            private: ::Windows::UI::Xaml::Controls::ListView^ alias_list;
            private: ::Microsoft::Advertising::WinRT::UI::AdControl^ ad;
            private: ::Windows::UI::Xaml::Controls::ListView^ VocList;
            private: ::Windows::UI::Xaml::Controls::ScrollViewer^ EditPanel;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ DelPanel;
            private: ::Windows::UI::Xaml::Controls::ListView^ DelList;
            private: ::Windows::UI::Xaml::Controls::TextBox^ block;
            private: ::Windows::UI::Xaml::Controls::ListView^ EditList;
            private: ::Windows::UI::Xaml::Controls::TextBox^ block2;
            private: ::Windows::UI::Xaml::Controls::ListView^ EditList2;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ pics;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ voc_croot;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ voc_root;
            private: ::Windows::UI::Xaml::Controls::AppBarButton^ fav;
        };
    }
}

